### ISSUE TITLE
model_segnet_dense.py

### ISSUE THREAD

**Issue by LYF14020510036** [lorenmt/mtan#1]
hello,could you tell me model_segnet_dense.py corresponds which paper?

**Comment by lorenmt** [comment]
Hi, baseline DENSE does not come from any paper. It was just a simple architecture we built from ourselves. DENSE has the largest parameter space and far larger than our proposed and other multi-task networks.. we do this in order to present the improved performance was not due to the larger parameter space but rather a better design.

**Comment by LYF14020510036** [comment]
Thank you very much.
