### ISSUE TITLE
preprocessing code

### ISSUE THREAD

**Issue by JingweiZhang12** [lorenmt/mtan#10]
Hi, @lorenmt . Thanks for your code! 
I'm following your work and have some questions. Considering you only show us your pre-processed label,  .npy  file , without any explanation, could you please provide your preprocessing code about original datasets? I want to know more details, such as data argumentation, calculation methods about normal  and  so on through your preprocessing code.

**Comment by lorenmt** [comment]
Hi,

I originally planned to release the pre-processing code. However, the code was unfortunately missing due to a computer crash. The pre-processing was not fancy but only to rescale the input image into a smaller resolution. And for NYUv2, we also crop out the invalid borders. The normals were directly extracted from the data here: https://cs.nyu.edu/~deigen/dnl/. There were no data argumentation, or cropping used to form the final datasets.

Hope that helps.

**Comment by JingweiZhang12** [comment]
Thanks for your reply!
