### ISSUE TITLE
depth label

### ISSUE THREAD

**Issue by JingweiZhang12** [lorenmt/mtan#12]
I noticed that your used depth is range in [-1,1], and you set invalid depth value as 0 so that a normal and depth ignored mask is used in your code [](https://cs.nyu.edu/~deigen/dnl/) . But from [NYUv2 dataset homepage](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2), I can't find any mask.
I want to know why you not use the original depth ranged in [0,10], which is used by many other depth estimation methods  and how you get the depth invalid mask.

**Comment by lorenmt** [comment]
Only normals are in the range [-1, 1] (measured by inverse cosine), all depth data are ground truth depth which should be >= 0 as measured by meters. Could you confirm that your depth data were fetched correctly?

The masks are defined here, in normals label (the link is provided in the readme as well): https://cs.nyu.edu/~deigen/dnl/

**Comment by JingweiZhang12** [comment]
Sorry for my negligence. You are right, only normals are in the range [-1, 1]. But the original ground truth depth in [](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2) are all >0, and the min{depth} is around 0.7, no depth = 0. Can you explain how get the depth invalid masks (depth=0) , because I find other depth estimation methods don't use  the depth invalid masks.

**Comment by lorenmt** [comment]
If I remember correctly, you can visualise the depth data and you will observe some discontinueties in some regions, and they are clearly artefacts (incorrect measurements). So I directly used the mask from the normals (directly downloable from the provided link) to mask out the invalid depth for consistency.


On Mon, Sep 30, 2019 at 23:37, JingweiZhang12 <notifications@github.com> wrote:
Sorry for my negligence. You are right, only normals are in the range [-1, 1]. But the original ground truth depth in [https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2] are all >0, and the min{depth} is around 0.7, no depth = 0. Can you explain how get the depth invalid masks (depth=0) , because I find other depth estimation methods don't use the depth invalid masks.

**Comment by JingweiZhang12** [comment]
Thanks for your timely reply. Are you sure normals mask can mask out all depth discontinue region  accurately and can't hurt valid depth data？I visualise the depth data you provided, I think normal masks may mask out  some valid depth data.

**Comment by lorenmt** [comment]
To be honest, I am not sure. But if we leave those artifacts to be part of training gradients, the model would unarguably receive wrong information. However, if we remove those discontinue regions (even with some additional correct regions), the training gradients are guaranteed to be correct.
You can decide by your own how to build your own datasets. As long as you keep the same format, you can still easily compare with my methods and other baselines.

On Tue, Oct 1, 2019 at 0:05, JingweiZhang12 <notifications@github.com> wrote:
Thanks for your timely reply. Are you sure normals mask can mask out all depth discontinue region accurately and can't hurt valid depth data？I visualise the depth data you provided, I think normal masks may mask out some valid depth data.

**Comment by JingweiZhang12** [comment]
OK. Thanks for your kindness!
